- docs/UserGuide.adoc
> Edit intro in UserGuide.adoc

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
> Change team name and date of changes for User and Developer Guide.

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/commons/core/Config.java
- src/main/java/seedu/address/ui/UiManager.java
- src/test/java/seedu/address/commons/core/ConfigTest.java
1. Edit application title
2. Edit application version
3. Set application to full screen only
> Minor UI Refinements

- docs/AboutUs.adoc
Some of the secondary roles and responsibliites are TBC.
> AbousUs.adoc: Edit roles and responsibilities.

- docs/AboutUs.adoc
> AboutUs.adoc: Edit incorrect format

- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/UiManager.java
There is an issue that the app would not go full screen. 
1. Fix bug by change the position of the code
2. Make the showing of full screen modular.
> Fix UI bug at main app launch

- docs/UserGuide.adoc
Updated UserGuide to replace instances of "AddressBook/Address Book" to "ClinicIO/Clinic Database" to suit ClinicIO.
Resolved #54
> [UserGuide.adoc] Edit UserGuide to complement ClinicIO

- docs/UserGuide.adoc
> Add login command into user guide.

- docs/UserGuide.adoc
> fix command formatting in user guide

- README.adoc
- Add BCrypt to the acknowledgement under library used.
> README.adoc: Edit libraries used.

- src/main/java/seedu/address/logic/commands/LoginCommand.java
- src/main/java/seedu/address/logic/parser/LoginCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/doctor/Password.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/XmlAdaptedDoctor.java
- src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
- src/test/java/seedu/address/commons/util/HashUtilTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/LoginCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/LoginCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/doctor/DoctorTest.java
- src/test/java/seedu/address/model/doctor/PasswordTest.java
- src/test/java/seedu/address/model/doctor/UniqueDoctorListTest.java
- src/test/java/seedu/address/storage/XmlAdapterDoctorTest.java
- src/test/java/seedu/address/testutil/DoctorBuilder.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
- Password login can now check with hashed password.
- Add test cases for
- Parsing Role
- Parsing Password
> Add login command

- docs/DeveloperGuide.adoc
**Do not merge this pull request. I will merge it myself**
- Add format for login authentication feature
> DeveloperGuide.adoc: Add login authentication feature implementation

- docs/UserGuide.adoc
- Edit introduction.
- Edit about this guide.
- Edit quick start (installation guide).
- Add User Interface walkthrough (WIP).
I will work on the UI walkthrough on another PR.
> UserGuide.adoc: Edit user guide

- src/main/java/seedu/address/logic/commands/AddApptCommand.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/analytics/Analytics.java
- src/main/java/seedu/address/model/analytics/Statistics.java
- src/main/java/seedu/address/model/analytics/TotalStatistics.java
- src/main/java/seedu/address/model/appointment/Appointment.java
- src/main/java/seedu/address/model/appointment/Date.java
- src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/model/appointment/AppointmentTest.java
- src/test/java/seedu/address/model/appointment/UniqueAppointmentListTest.java
- src/test/java/seedu/address/testutil/AppointmentBuilder.java
Changes:
- Appointment has a type field to indicate if it is a follow-up
- UniqueAppointmentList is initialized with Analytics
- Date has a method to check if an appointment falls in the current real life week
- TotalStatistics has methods to compute statistics related to appointments
> Add analytics support for appointments

- src/main/java/seedu/address/model/Consultation.java
Opening this pr to check if this representation of consultation is alright before I continue working with it
> add consultation

- src/main/java/seedu/address/MainApp.java
**URGENTLY** Must push this ASAP.
> Move from v1.2 to v1.2.1

- src/test/java/seedu/address/ui/PersonListPanelTest.java
Refer to  #https://github.com/se-edu/addressbook-level4/pull/918/commits/3eb588bafdc5e5683080cfca655f24d60356d905 for full commit message
Issue added at #110 
[Fix #110]
> PersonListPanelTest.java: Fix bug from SE-EDU AB Lvl 4 [Fix #110]

- _reposense/config.json
- Add new author names
- Edit display name
Fix reposense commit not showing. I call all of u to oso check ur reposense and edit here,
> Edit config.json

- src/main/resources/view/LightTheme.css
Fix #115
Help view and suggest.
> Edit color when hover over the card in PersonList.

- docs/DeveloperGuide.adoc
Update based on Diana's feedback on this morning - 1/11 Thursday. 
Consistency of sentence, and some grammatical weirdness.
> Update dev guide

- docs/DeveloperGuide.adoc
- docs/team/jjlee050.adoc
- Edit summary of contributions and contributions to UG/DG
> Update Project Portfolio Page

- docs/UserGuide.adoc
**URGENT**
Edit example to allow user to have sample account to test
> Edit examples for login

- src/main/java/seedu/clinicio/logic/commands/LoginCommand.java
- src/main/java/seedu/clinicio/logic/parser/ParserUtil.java
- src/main/java/seedu/clinicio/model/staff/Password.java
- Fix #193 : Update message usage for login.
- Fix #194 & #199 : Update the message for password constraints to deal with < 6 and more than >12 characters.
> Fix bugs found in PE with regards to login

- src/main/java/seedu/clinicio/commons/core/UserSession.java
- src/main/java/seedu/clinicio/commons/events/ui/LoginSuccessEvent.java
- src/main/java/seedu/clinicio/commons/events/ui/NewResultAvailableEvent.java
- src/main/java/seedu/clinicio/ui/CommandBox.java
- src/main/java/seedu/clinicio/ui/ResultDisplay.java
- src/main/java/seedu/clinicio/ui/StatusBarFooter.java
- src/main/java/seedu/clinicio/ui/util/PasswordPrefixFormatter.java
- src/test/java/seedu/clinicio/ui/ResultDisplayTest.java
- Fix #196 : Add color to show for password invalid and result display.
- Fix #219 : Fix password censorship of showing 2 letters.
> Fix login bugs found in PE dry run

- docs/UserGuide.adoc
- src/main/java/seedu/clinicio/logic/commands/AddPatientCommand.java
- src/main/java/seedu/clinicio/logic/parser/CliSyntax.java
- src/main/java/seedu/clinicio/model/patient/Patient.java
- src/test/java/seedu/clinicio/logic/commands/AddPatientCommandIntegrationTest.java
- src/test/java/seedu/clinicio/logic/commands/AddPatientCommandTest.java
- src/test/java/seedu/clinicio/model/appointment/AppointmentTest.java
- src/test/java/seedu/clinicio/model/patient/PatientTest.java
- Check if the preferred doctor is a doctor
- Check if user is login as a receptionist
- Edit user guide.
- Edit test cases
> Implement Add patient command (III)

- src/main/java/seedu/clinicio/ui/CommandBox.java
- src/main/java/seedu/clinicio/ui/util/PasswordPrefixFormatter.java
- src/test/java/seedu/clinicio/ui/util/PasswordPrefixFormatterTest.java
Working on improving test coverage
(Currently: 71% - 72%)
UI
- `PasswordPrefixFormatterTest.java`
> Improve test coverage for ClinicIO

- src/main/java/seedu/clinicio/commons/core/Messages.java
- src/main/java/seedu/clinicio/logic/commands/AddMedicineCommand.java
- src/main/java/seedu/clinicio/logic/commands/AddPatientCommand.java
- src/main/java/seedu/clinicio/logic/commands/DeleteMedicineCommand.java
- src/main/java/seedu/clinicio/logic/commands/FindMedicineCommand.java
- src/main/java/seedu/clinicio/logic/commands/ListMedicineCommand.java
- src/test/java/seedu/clinicio/logic/commands/AddMedicineCommandIntegrationTest.java
- src/test/java/seedu/clinicio/logic/commands/AddMedicineCommandTest.java
- src/test/java/seedu/clinicio/logic/commands/AddPatientCommandTest.java
- src/test/java/seedu/clinicio/logic/commands/DeleteMedicineCommandTest.java
Require login status for the following commands:
1. `AddMedicineCommand`
2. `DeleteMedicineCommand`
Edited test files
1. `AddMedicineCommandTest`
2. `DeleteMedicineCommandTest`
> Require login for Medicine Commands

- src/main/java/seedu/clinicio/commons/core/Messages.java
- src/main/java/seedu/clinicio/logic/commands/FindPatientCommand.java
- src/main/java/seedu/clinicio/logic/commands/ListPatientCommand.java
- src/main/java/seedu/clinicio/logic/parser/ClinicIoParser.java
- src/main/java/seedu/clinicio/logic/parser/FindPatientCommandParser.java
- src/main/java/seedu/clinicio/model/patient/PatientNameContainsKeywordsPredicate.java
- src/test/java/seedu/clinicio/logic/commands/AddPatientCommandTest.java
- src/test/java/seedu/clinicio/logic/commands/FindPatientCommandTest.java
- src/test/java/seedu/clinicio/logic/parser/ClinicIoParserTest.java
- src/test/java/seedu/clinicio/logic/parser/FindPatientCommandParserTest.java
- src/test/java/seedu/clinicio/model/patient/PatientNameContainsKeywordsPredicateTest.java
Add ListPatientCommand and test cases
Add FindPatientCommand and test cases
> Implement List and Find Patient

- src/main/java/seedu/clinicio/MainApp.java
> Edit version  v1.3 to v1.4

- docs/UserGuide.adoc
Edit introduction.
Add implemented methods.
> Edit user guide 

- src/main/java/seedu/clinicio/logic/commands/LoginCommand.java
> Tidy up Logic

- docs/team/jjlee050.adoc
> Make final changes to PPP

- docs/DeveloperGuide.adoc
> Fix broken links and images.

- docs/UserGuide.adoc
section 6.4 queue to showqueue
> fix userguide

- src/main/java/seedu/clinicio/logic/commands/AddPatientCommand.java
- src/main/java/seedu/clinicio/logic/commands/DeleteMedicineCommand.java
- src/main/java/seedu/clinicio/logic/commands/FindPatientCommand.java
- src/main/java/seedu/clinicio/logic/commands/ListAllApptCommand.java
- src/main/java/seedu/clinicio/logic/commands/ListPatientCommand.java
- src/main/resources/view/PatientListCard.fxml
- add switchtab event to relevant commands (listpatient)
- patientlistcard visibible
> Listpatient
